package api_builder.bean;
// Generated 20 nov. 2017 11:07:17 by Hibernate Tools 5.2.6.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conducteur generated by hbm2java
 */
@Entity
@Table(name="conducteur"
)
public class Conducteur  implements java.io.Serializable {


     private int idconducteur;
     private String nom;
     private String prenom;
     private Date age;
     private Set<Voiture> voitures = new HashSet<Voiture>(0);

    public Conducteur() {
    }

	
    public Conducteur(int idconducteur) {
        this.idconducteur = idconducteur;
    }
    public Conducteur(int idconducteur, String nom, String prenom, Date age, Set<Voiture> voitures) {
       this.idconducteur = idconducteur;
       this.nom = nom;
       this.prenom = prenom;
       this.age = age;
       this.voitures = voitures;
    }
   
     @Id 

    
    @Column(name="idconducteur", unique=true, nullable=false)
    public int getIdconducteur() {
        return this.idconducteur;
    }
    
    public void setIdconducteur(int idconducteur) {
        this.idconducteur = idconducteur;
    }

    
    @Column(name="nom", length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", length=45)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="age", length=10)
    public Date getAge() {
        return this.age;
    }
    
    public void setAge(Date age) {
        this.age = age;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conducteur")
    public Set<Voiture> getVoitures() {
        return this.voitures;
    }
    
    public void setVoitures(Set<Voiture> voitures) {
        this.voitures = voitures;
    }




}


