package api_builder.bean;
// Generated 21 nov. 2017 17:06:39 by Hibernate Tools 5.2.6.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roue generated by hbm2java
 */
@Entity
@Table(name="roue"
)
public class Roue  implements java.io.Serializable {


     private int idroue;
     private Long rayon;
     private Double largeur;
     private Set voitureRoues = new HashSet(0);

    public Roue() {
    }

	
    public Roue(int idroue) {
        this.idroue = idroue;
    }
    public Roue(int idroue, Long rayon, Double largeur, Set voitureRoues) {
       this.idroue = idroue;
       this.rayon = rayon;
       this.largeur = largeur;
       this.voitureRoues = voitureRoues;
    }
   
     @Id 

    
    @Column(name="idroue", unique=true, nullable=false)
    public int getIdroue() {
        return this.idroue;
    }
    
    public void setIdroue(int idroue) {
        this.idroue = idroue;
    }

    
    @Column(name="rayon", precision=10, scale=0)
    public Long getRayon() {
        return this.rayon;
    }
    
    public void setRayon(Long rayon) {
        this.rayon = rayon;
    }

    
    @Column(name="largeur", precision=22, scale=0)
    public Double getLargeur() {
        return this.largeur;
    }
    
    public void setLargeur(Double largeur) {
        this.largeur = largeur;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roue")
    public Set getVoitureRoues() {
        return this.voitureRoues;
    }
    
    public void setVoitureRoues(Set voitureRoues) {
        this.voitureRoues = voitureRoues;
    }




}


