package api_builder.bean;
// Generated 8 févr. 2018 16:16:09 by Hibernate Tools 6.0.0-SNAPSHOT

import api_builder.jackson.Views;
import com.fasterxml.jackson.annotation.JsonView;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conducteur generated by hbm2java
 */
@Entity
@Table(name="conducteur"
)
public class Conducteur  implements java.io.Serializable {


     private Integer idconducteur;
     private String nom;
     private String prenom;
     private Date age;
     private Set<Voiture> voitures = new HashSet<Voiture>(0);

    public Conducteur() {
    }

    public Conducteur(String nom, String prenom, Date age, Set<Voiture> voitures) {
       this.nom = nom;
       this.prenom = prenom;
       this.age = age;
       this.voitures = voitures;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idconducteur", unique=true, nullable=false)
    @JsonView(Views.ConducteurView.class)
    public Integer getIdconducteur() {
        return this.idconducteur;
    }
    
    public void setIdconducteur(Integer idconducteur) {
        this.idconducteur = idconducteur;
    }

    
    @Column(name="nom", length=45)
    @JsonView(Views.ConducteurView.class)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", length=45)
    @JsonView(Views.ConducteurView.class)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="age", length=10)
    @JsonView(Views.ConducteurView.class)
    public Date getAge() {
        return this.age;
    }
    
    public void setAge(Date age) {
        this.age = age;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conducteur")
    @JsonView(Views.ConducteurView.class)
    public Set<Voiture> getVoitures() {
        return this.voitures;
    }
    
    public void setVoitures(Set<Voiture> voitures) {
        this.voitures = voitures;
    }




}


